from __future__ import annotations

from .diagnostics import TranslationResult
from .ir import ProgramIR
from .pyspark_emitter import emit_pyspark


def emit_databricks(program: ProgramIR) -> TranslationResult:
    result = emit_pyspark(program)
    header = [
        "# Databricks notebook source",
        "# Generated by sas-migrator with target=databricks.",
        "# Configure catalog/schema, cluster policy, secrets, and job orchestration before production use.",
        "# COMMAND ----------",
        "",
        "dbutils.widgets.text('catalog', '')",
        "dbutils.widgets.text('schema', '')",
        "catalog = dbutils.widgets.get('catalog')",
        "schema = dbutils.widgets.get('schema')",
        "if catalog and schema:",
        "    spark.sql(f'USE CATALOG {catalog}')",
        "    spark.sql(f'USE SCHEMA {schema}')",
        "",
        "# COMMAND ----------",
        "",
    ]
    footer = [
        "",
        "# COMMAND ----------",
        "# Optional materialization point, similar in spirit to forcing a SAS step boundary.",
        "# Uncomment per job after deciding which DataFrames should be persisted/checkpointed.",
        "# spark.sparkContext.setCheckpointDir('/tmp/sas_migrator_checkpoints')",
        "# <dataframe_name> = <dataframe_name>.checkpoint(eager=True)",
    ]
    code = "\n".join(header) + result.code + "\n".join(footer) + "\n"
    result.report.add(
        "info",
        "databricks_target",
        "Databricks output wraps PySpark code with notebook widgets for catalog/schema and checkpoint guidance.",
        "databricks",
    )
    return TranslationResult(code=code, report=result.report)
